<a href="https://colab.research.google.com/github/Ganeshgampa09/python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
1)Numpy stands for Numerical python.
2)NumPy is a Python library used for working with arrays.

#There are 6 ways to creating arrays:-
1)using np.array() //1-D or 2-Dimensional

2)using np.ones() // zeros // empty // random()

3)using np.identiy()

4)using np.arange()

5)using np.copy()

6)using np.linspace()

#Important attributes and properties.
1)shape

2)ndim

3)size

4)itemsize

5)Dtype

6)astype()

In [75]:
import numpy as np
arr1=np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3=np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr6=np.arange(20)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arr6=np.arange(1,20,2)
arr6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
arr7=np.linspace(10,20,5)
arr7

array([10. , 12.5, 15. , 17.5, 20. ])

In [19]:
arr8=np.copy(arr7)
arr8

array([10. , 12.5, 15. , 17.5, 20. ])

#attributes and properties.

In [24]:
#1)shape
arr1.shape

(4,)

In [25]:
arr2.shape

(2, 3)

In [26]:
#we will create 3-D array
arr9=np.array([ [[1,2],[2,3]],[[4,5],[6,7]]])
arr9

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
arr9.shape

(2, 2, 2)

In [29]:
#arr9 is a 3-D aray if we don't know we can see the dimension of an array by ndim.
arr9.ndim

3

In [30]:
arr2.ndim

2

In [31]:
#3)size :- if we don't know the size of an array we can use size attribute.
arr1.size

4

In [32]:
arr9.size

8

In [33]:
arr1.itemsize

8

In [42]:
arr1.dtype

dtype('int64')

In [45]:
arr10=np.arange(25).reshape(5,5)
arr10

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr10[0]

array([0, 1, 2, 3, 4])

In [49]:
arr10[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
arr10[:,3]

array([ 3,  8, 13, 18, 23])

In [52]:
for i in np.nditer(arr10):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [53]:
arr12=np.array([1,2,3,4,5])
arr13=np.array([6,7,8,9,10])

In [54]:
arr12-arr13

array([-5, -5, -5, -5, -5])

In [56]:
arr12*arr13

array([ 6, 14, 24, 36, 50])

In [57]:
arr12+arr13

array([ 7,  9, 11, 13, 15])

In [58]:
arr12*2

array([ 2,  4,  6,  8, 10])

In [59]:
arr12>2

array([False, False,  True,  True,  True])

In [65]:
arr2.ndim

2

#Ravel function is used to convert the 2dimensional array into 1 dimensional array.

In [67]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

We have not used inplace=true so the changes are temparary.

In [66]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6])

In [68]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr2.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

#Fancy indexing.

In [71]:
arr10

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
arr10[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

#It will extract all the elements in the array.

In [74]:
arr10[arr10>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])